.PHONY: clean ensure_logs ensure_figures
ensure_logs:
	mkdir -p logs

ensure_figures:
	mkdir -p figures

clean:
	rm -rf logs/*
	rm -rf figures/*
	rm -f  visualization.html
	rm -f  prediction.html
	rm -f  tsa_prediction.csv

tsa_prediction.csv figures/plot1 figures/plot2 figures/plot3: visualization.R utils.R
	Rscript visualization.R

logs/logs_output1 logs/logs_output2: prediction.R
	Rscript prediction.R

visualization.html: figures/plot1 figures/plot2 figures/plot3 
	Rscript -e "rmarkdown::render('visualization.Rmd', output_file='visualization.html')"

prediction.html: logs/logs_output1 logs/logs_output2 tsa_prediction.csv
	Rscript -e "rmarkdown::render('prediction.Rmd', output_file='prediction.html')"





